# -*- coding: utf-8 -*-
"""final_strategy_group2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7zl2Xu66KbeBOnNycd6Uy3qnPKPETVU
"""

!git clone https://github.com/sevintanerdi/HFD_project.git

!pip install quantstats

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import quantstats as qs

# Settings0
quarters = [
    "2023_Q1", "2023_Q3", "2023_Q4",
    "2024_Q2", "2024_Q4",
    "2025_Q1", "2025_Q2"
]

POINT_VALUE = 100
TCOST = 15

# function
def mySR(x, scale):
    return np.sqrt(scale) * np.nanmean(x) / np.nanstd(x)

# summary container
summary_group2_final = pd.DataFrame()

def calmar_from_pnl(daily_pnl, scale=252):
    cum_pnl = daily_pnl.cumsum()
    drawdown = cum_pnl - cum_pnl.cummax()
    max_dd = drawdown.min()
    if max_dd == 0:
        return np.nan
    return (daily_pnl.mean() * scale) / abs(max_dd)

for quarter in quarters:

    data = pd.read_parquet(
        f"/content/HFD_project/data_processed/group2_processed/data2_{quarter}_processed.parquet"
    )

    pos_flat = data["pos_flat"].values

    fastEMA = data["XAU"].ewm(span=20).mean()
    slowEMA = data["XAU"].ewm(span=100).mean()

    cond_long = fastEMA.shift(1) > slowEMA.shift(1)
    valid = fastEMA.shift(1).notna() & slowEMA.shift(1).notna()

    pos = np.where(valid, np.where(cond_long, 1, -1), np.nan)
    pos[pos_flat == 1] = 0

    pnl_gross = np.where(
        np.isnan(pos * data["XAU"].diff()),
        0,
        pos * data["XAU"].diff() * POINT_VALUE
    )

    ntrans = np.abs(np.diff(pos, prepend=0))
    pnl_net = pnl_gross - ntrans * TCOST

    pnl_gross_d = pd.Series(pnl_gross).groupby(data.index.date).sum()
    pnl_net_d   = pd.Series(pnl_net).groupby(data.index.date).sum()
    ntrans_d    = pd.Series(ntrans).groupby(data.index.date).sum()

    gross_SR = mySR(pnl_gross_d, 252)
    net_SR   = mySR(pnl_net_d, 252)

    gross_CR = calmar_from_pnl(pnl_gross_d)
    net_CR   = calmar_from_pnl(pnl_net_d)

    gross_PnL = pnl_gross_d.sum()
    net_PnL   = pnl_net_d.sum()

    av_daily_ntrans = ntrans_d.mean()

    stat = (net_SR - 0.5) * np.maximum(
        0, np.log(np.abs(net_PnL / 1000))
    )

    summary = pd.DataFrame({
        "quarter": quarter,
        "strategy": "momentum",
        "params": "EMA20-100",
        "gross_SR": gross_SR,
        "net_SR": net_SR,
        "gross_PnL": gross_PnL,
        "net_PnL": net_PnL,
        "gross_CR": gross_CR,
        "net_CR": net_CR,
        "av_daily_ntrans": av_daily_ntrans,
        "stat": stat
    }, index=[0])

    summary_group2_final = pd.concat(
        [summary_group2_final, summary],
        ignore_index=True
    )

    plt.figure(figsize=(12, 6))
    plt.plot(np.cumsum(pnl_gross_d.fillna(0)), label="Gross PnL")
    plt.plot(np.cumsum(pnl_net_d.fillna(0)), label="Net PnL")
    plt.title(f"XAU EMA(20,100) – {quarter}")
    plt.xlabel("Date")
    plt.ylabel("Cumulative PnL (USD)")
    plt.legend()
    plt.show()
    plt.savefig(f"/content/HFD_project/outputs/XAU_EMA20_100_{quarter}.png", dpi=300)
    plt.close()

summary_group2_final

summary_group2_final.to_csv(
    "/content/HFD_project/outputs/summary_group2_XAU_EMA20_100.csv",
    index=False
)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(14, 4))
ax.axis("off")

table = ax.table(
    cellText=summary_group2_final.round(3).values,
    colLabels=summary_group2_final.columns,
    loc="center"
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.5)

plt.savefig(
    "/content/HFD_project/outputs/summary_stats_group2.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()